joint_position_example_controller:
    type: flexiv_example_controllers/JointPositionExampleController
    joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
        - joint7